[package]
name = "Game"
version = "0.1.0"
edition = "2024"

[dependencies]
WEngine = { path = "../WEngine" }
anyhow = "1.0.100"
nalgebra = "0.34.1"
rand = "0.9.2"
winit = "0.30.12"

[[bin]]
name = "game"
path = "src/main.rs"
